call npm install gulp
call npm install gulp-uglifyjs
call npm install gulp-concat-sourcemap
call npm install gulp-autoprefixer
call npm install gulp-minify-css
call npm install gulp-compass
call npm install gulp-notify
call npm install gulp-rename
call npm install gulp-clean